name: Release

on:
  push:
    branches:
      - main

jobs:
  xmllint:
    runs-on: ubuntu-latest
    steps:
      # Check out this repository
      - uses: actions/checkout@v2

      - name: Install xmllint
        run: |
          apt-get update
          apt-get install -y libxml2-utils

      - name: Get SVD schema
        run: |
          curl -o CMSIS-SVD.xsd https://raw.githubusercontent.com/ARM-software/CMSIS_5/develop/CMSIS/Utilities/CMSIS-SVD.xsd

      - name: Check all SVD files against schema
        shell: bash
        run: |
          exit_status=0
          for svd in ./svd/*.svd; do
            xmllint --noout --schema CMSIS-SVD.xsd $svd || exit_status=$?
          done
          exit $exit_status


  release:
    runs-on: ubuntu-latest
    steps:
      # Check out this repository
      - uses: actions/checkout@v2

      # Determine the current date, used for the tag and release name
      - name: Determine current date
        run: |
          echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Create a release containing all SVDs and using the current date as the
      # tag/release name
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "svd/*.svd"
          tag: ${{ env.CURRENT_DATE }}
